-- Create dbo.Users
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Users')
BEGIN
CREATE TABLE dbo.Users
(
UserID INT IDENTITY(1,1) CONSTRAINT PK_Users PRIMARY KEY NOT NULL,
FirstName VARCHAR(20) NOT NULL,
LastName VARCHAR(20) NOT NULL,
DateOfBirth DATE,
EmailAddress VARCHAR(100) NOT NULL,
PhoneNumber VARCHAR(20),
Password Varchar(18),
CreatedDate DATETIME,
CreatedBy VARCHAR(100),
ModifiedDate DATETIME,
ModifiedBy VARCHAR(100)
);
END
GO

-- Create dbo.Movies
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Movies')
BEGIN
CREATE TABLE dbo.Movies
(
MovieID INT NOT NULL,
GenreID INT NOT NULL,
LanguageID INT NOT NULL,
MovieTitle VARCHAR(100) NOT NULL,
MovieDesc VARCHAR(1000),
IMDBRating Decimal(2,1),
RTRating Decimal(2,1),
CreatedDate DATETIME,
CreatedBy VARCHAR(100),
ModifiedDate DATETIME,
ModifiedBy VARCHAR(100)
);


ALTER TABLE dbo.Movies
ADD CONSTRAINT PK_Movies PRIMARY KEY (MovieID);
END
GO


--Create dbo.MovieReviews
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MovieReviews')
BEGIN
CREATE TABLE dbo.MovieReviews
(
MovieReviewID INT IDENTITY(1,1) CONSTRAINT PK_UserPreferences PRIMARY KEY NOT NULL,
MovieID INT NOT NULL,
MovieReviewDesc VARCHAR(MAX) NOT NULL,
CreatedDate DATETIME,
CreatedBy VARCHAR(100),
ModifiedDate DATETIME,
ModifiedBy VARCHAR(100)
);
END
GO

-- Create dbo.Genres
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Genres')
BEGIN
CREATE TABLE dbo.Genres
(
GenreID INT NOT NULL,
GenreName VARCHAR(15) NOT NULL
);

ALTER TABLE dbo.Genres
ADD CONSTRAINT PK_Genres PRIMARY KEY (GenreID);
END
GO

-- Create dbo.Movie_Genre
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Movie_Genre')
BEGIN
CREATE TABLE dbo.Movie_Genre
(
MovieID INT NOT NULL,
GenreID INT NOT NULL
);

ALTER TABLE dbo.Movie_Genre
ADD CONSTRAINT PK_Movie_Genre PRIMARY KEY (MovieID, GenreID);
END
GO


-- Create dbo.UserPreferences
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'UserPreferences')
BEGIN
CREATE TABLE dbo.UserPreferences
(
UserPreferenceID INT IDENTITY(1,1) CONSTRAINT PK_UserPreferences PRIMARY KEY NOT NULL,
UserID INT NOT NULL,
LanguageID INT NOT NULL,
GenreID INT NOT NULL,
CreatedDate DATETIME,
CreatedBy VARCHAR(100),
ModifiedDate DATETIME,
ModifiedBy VARCHAR(100)
);
END
GO

-- Create dbo.Languages
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Languages')
BEGIN
CREATE TABLE dbo.Languages
(
LanguageID INT IDENTITY(1,1) CONSTRAINT PK_Languages PRIMARY KEY NOT NULL,
LanguageABBR VARCHAR(2) NOT NULL,
LanguageName VARCHAR(20) NOT NULL
);
END
GO

--Create dbo.StreamingPlatforms
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'StreamingPlatforms')
BEGIN
CREATE TABLE dbo.StreamingPlatforms
(
SPID INT IDENTITY(1,1) CONSTRAINT PK_StreamingPlatforms PRIMARY KEY NOT NULL,
SPName VARCHAR(20) NOT NULL
);
END
GO

--Create dbo.Movie_StreamingPlatforms
IF NOT EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Movie_StreamingPlatforms')
BEGIN
CREATE TABLE dbo.Movie_StreamingPlatforms
(
MSPID INT IDENTITY(1,1) CONSTRAINT PK_Movie_StreamingPlatforms PRIMARY KEY NOT NULL,
SPID INT NOT NULL,
MovieID INT NOT NULL
);
END
GO